"""Criando tabelas

Revision ID: 298239d8a77d
Revises: 135f27b4fac9
Create Date: 2026-06-02 11:19:18.063780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298239d8a77d'
down_revision: Union[str, Sequence[str], None] = '135f27b4fac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('is_associado', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_table('itens_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('produto_nome', sa.String(length=150), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_venda_id'), 'itens_venda', ['id'], unique=False)
    op.add_column('vendas', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('vendas', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('vendas', sa.Column('desconto_percentual', sa.Float(), nullable=False))
    op.add_column('vendas', sa.Column('total_bruto', sa.Float(), nullable=False))
    op.add_column('vendas', sa.Column('total_liquido', sa.Float(), nullable=False))
    op.add_column('vendas', sa.Column('observacao', sa.String(length=255), nullable=True))
    op.add_column('vendas', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_index(op.f('ix_vendas_id'), 'vendas', ['id'], unique=False)
    op.create_foreign_key(None, 'vendas', 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'vendas', 'clientes', ['cliente_id'], ['id'], ondelete='SET NULL')
    op.drop_column('vendas', 'valor_final')
    op.drop_column('vendas', 'data')
    op.drop_column('vendas', 'desconto')
    op.drop_column('vendas', 'valor_total')
    op.drop_column('vendas', 'metodo_pagamento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('metodo_pagamento', sa.VARCHAR(length=150), nullable=False))
    op.add_column('vendas', sa.Column('valor_total', sa.FLOAT(), nullable=False))
    op.add_column('vendas', sa.Column('desconto', sa.FLOAT(), nullable=True))
    op.add_column('vendas', sa.Column('data', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('vendas', sa.Column('valor_final', sa.FLOAT(), nullable=False))
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.drop_index(op.f('ix_vendas_id'), table_name='vendas')
    op.drop_column('vendas', 'criado_em')
    op.drop_column('vendas', 'observacao')
    op.drop_column('vendas', 'total_liquido')
    op.drop_column('vendas', 'total_bruto')
    op.drop_column('vendas', 'desconto_percentual')
    op.drop_column('vendas', 'usuario_id')
    op.drop_column('vendas', 'cliente_id')
    op.drop_index(op.f('ix_itens_venda_id'), table_name='itens_venda')
    op.drop_table('itens_venda')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
