"""Criando tabelas

Revision ID: c5f9fb8ad1d5
Revises: c82e6a1f4d30
Create Date: 2026-08-11 14:30:25.151848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f9fb8ad1d5'
down_revision: Union[str, Sequence[str], None] = 'c82e6a1f4d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
