"""Criando tabelas

Revision ID: e2a9d4a10fa9
Revises: f2b7c1d4e8a9
Create Date: 2026-09-21 10:44:03.497421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a9d4a10fa9'
down_revision: Union[str, Sequence[str], None] = 'f2b7c1d4e8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
